### PR TITLE
finished working on draft of report view

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #128 

## Changes in this PR.

- [X] Modified app.rb to make a `report/` endpoint
- [X] Created a `views/report.erb` for the view
- [ ] Test?

## Testing this PR.

1. Do `docker compose up` or `docker-compose run dev bash` then `rake`.
2. Do go to `localhost:4567/report`.
3. See page.

### Expected Output.

This view has been generated with test data!!!
Screenshot IMAGE: [iam_report_view](https://cloud.githubusercontent.com/assets/7299081/17006641/18d37f30-4e97-11e6-8ec3-866c8ca75a32.png)

@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
blocked my #132 and #125

**Comment by alxngyn** [comment]
Updated node view to be in table form
[image](https://cloud.githubusercontent.com/assets/7299081/17120337/5fcb5c22-5280-11e6-970e-81730c56cf1b.png)

**Comment by ElijahCaine** [comment]
I don't see anything wrong with this. We'll need to cleanup the views eventually but I'd rather get something done that we can tweak. If we labor over it now it'll never get done.

**Comment by hsolorza** [comment]
+1

**Pull request merged**
