### PR TITLE
Hsolorza/edit changes

### PR DESCRIPTION
**Pull request by hsolorza**
fixes issue #288 

## Changes in this PR.

- [X] Creates dropdown for node/db project edit

## Testing this PR.

1. Create node/ db
2. Assign the node/db a project
3. Edit the node/db to have a different project
4. See the updated project assignment

NOTE: this PR only works correctly if the caching is deactivated
### Expected Output.

```
$ rake spec
[...]
```

@osuosl/devs

### CODE REVIEW

**Review by alxngyn — APPROVED** [review]
looks good.
works as described

**Comment by panntomime** [comment]
The form control looks good, but it doesn't look like the project is updating on the Node Detail page -- Is that expected behavior?

**Comment by hsolorza** [comment]
@panntomime  I think that occurs because of the caching. If you disable it (in app.rb and config.rb) it should work.

**Review by baileysingleton — APPROVED** [review]
Everything works as specified, after I commented out the cache that is 📦 
++

**Pull request merged**
