### PR TITLE
fixed migrate task to migrate to the latest version

### PR DESCRIPTION
**Pull request by alxngyn**
- the version symbol was giving errors so i took it out completely
 - we can add it back once we have versions to work off of 

## Changes in this PR.

- [X] Fixed rakefile tasks: migrate

## Testing this PR.

1. Run `docker-compose run dev bash`
2. run `rake` or run `rake migrate`
 * You can also run `rake migrate[#]` where # is the migrate version you want to target
3. Results should update the DB schema and run the app.rb

@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
Looks like @ElijahCaine fixed the "Don't know how to build task 'version'" error with this commit:
https://github.com/osuosl/iam/commit/f79a0cc9c645fabeedac5af7a55c4ee219cc1ea9

However, it looks like we still need to change the single quotes on line 14 to double to make the version number print correctly. I'll change this PR to reflect that.

**Comment by Kennric** [comment]
@alxngyn I think this is good, but please rebase and resolve conflicts

**Comment by alxngyn** [comment]
fixed conflicts

**Comment by Kennric** [comment]
Looks good to me. +1

**Comment by ElijahCaine** [comment]
Yep, looks good to me :+1:

**Comment by ElijahCaine** [comment]
-1
```
[root@7d557138010a code]# rake migrate
rake aborted!
NoMethodError: undefined method `[]' for <Rake::Task migrate => []>:Rake::Task
/data/code/Rakefile:13:in `block in <top (required)>'
Tasks: TOP => migrate
(See full trace by running task with --trace)
```

**Comment by alxngyn** [comment]
OK looks like PR #40 undid a fix to the Rakefile. Looks like I need to review over PRs more closely.

Updated PR with the fix.
Expected output:
```
[root@308f16020cdb code]# rake
Migrating to latest
/usr/local/bin/ruby app.rb
[root@308f16020cdb code]# rake migrate
rake Migrating to latest
[root@308f16020cdb code]# rake migrate[1]
Migrating to version 1
```

@ElijahCaine @matthewrsj @Kennric

**Comment by ElijahCaine** [comment]
@alxngyn Looks good to me. +1

**Comment by Kennric** [comment]
+1

**Pull request merged**
