### PR TITLE
Add store method for disk_sizes plugin

### LINKED ISSUE #30: Create Store Method for disk_sizes Plugin [5]
The `collect` method performs the following tasks when called by the rufus scheduler:

1. Pull `disk_sizes` information for the specified node out of redis.
2. Sum all `disk_sizes` values (`disk_sizes` is a list of integers).
3. Store `sum` in the `disk_sizes_measurements` table in the database.

### LINKED ISSUE #32: Create Register Method for disk_sizes Plugin [3]
The `register` method performs the following tasks whenever called by the scheduler:

* Adds self to `Plugins` table.
* Create a table in the database for this measurement if a table does not already exist.
* Run plugin migrations.

### LINKED ISSUE #33: Create disk_sizes plugin migrations file [1]
Straightforward. Should live in same directory as the `disk_sizes` plugin.

### PR DESCRIPTION
**Pull request by matthewrsj**
Fixes #30 
Fixes #32 
Fixes #33 

## Changes in this PR.

- [x] Create store method for disk_sizes plugin
- [x] Schedule the disk_sizes plugin store method
- [x] Tests the store method
- [x] Creates the register method
- [x] Creates the migrations file

## Testing this PR.

1. `docker-compose run dev bash` after making sure your app.env is correct
2. `rake spec`

***OR*** (a more hands-on method)

1. `docker-compose run dev bash` after making sure your app.env is correct
2. On line 15 of scheduler.rb change `'15m'` to `4`. Note you need to remove the quotes. You can also `puts` something after the `.each` loop if you want to see when it is finished.
4. `rake migrate && ruby scheduler.rb` then wait 15-20 seconds before pressing CTRL-C (it does it's work silently and immediately, then every 30 minutes). If you added a `puts` statement above you will see it when this finishes.
7. Open sqlite3 database, `sqlite3 /tmp/development.sqlite`
8. `select * from disk_size_measurements;`

You should see something like this:
```
1||2016-05-06 22:17:15.453218|mandrivausers2.osuosl.org|12800|1
2||2016-05-06 22:17:15.631977|deluge.osuosl.org|20480|1
3||2016-05-06 22:17:15.817240|rtvstaging2-web.osuosl.org|10752|1
4||2016-05-06 22:17:15.995706|efs.osuosl.org|11264|1
5||2016-05-06 22:17:16.166123|fossology.osuosl.org|15360|1
6||2016-05-06 22:17:16.349770|pgd-app1.osuosl.org|15360|1
7||2016-05-06 22:17:16.533202|systers-prod.osuosl.org|20480|1
8||2016-05-06 22:17:16.717963|jaws2.osuosl.org|16384|1
9||2016-05-06 22:17:16.903161|oprod-controller.osuosl.org|10240|1
10||2016-05-06 22:17:17.059477|teadmin-r.osuosl.org|5120|1
11||2016-05-06 22:17:17.217986|spacewalk.osuosl.org|40960|1
12||2016-05-06 22:17:17.629046|rtvprodvr-util.osuosl.org|38912|1
13||2016-05-06 22:17:17.793969|connectopensource.osuosl.org|20480|1
14||2016-05-06 22:17:17.952897|crosstool-ng.osuosl.org|10752|1
...
```

I get 187 lines.

@osuosl/devs

### CODE REVIEW

**Comment by ElijahCaine** [comment]
@matthewrsj When I run the hands on instructions I get the following error object printed to the screen:
```
{ 70284179437800 rufus-scheduler intercepted an error:
  70284179437800   job:
  70284179437800     Rufus::Scheduler::EveryJob "30m" {:first_in=>4}
  70284179437800   error:
  70284179437800     70284179437800
  70284179437800     NameError
  70284179437800     undefined local variable or method `key' for main:Object
  70284179437800       scheduler.rb:23:in `block in <main>'
  70284179437800       /usr/local/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  70284179437800       /usr/local/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  70284179437800       /usr/local/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
  70284179437800       /usr/local/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
  70284179437800       /usr/local/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/jobs.rb:289:in `loop'
  70284179437800       /usr/local/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
  70284179437800   tz:
  70284179437800     ENV['TZ']: 
  70284179437800     Time.now: 2016-05-09 21:22:37 +0000
  70284179437800   scheduler:
  70284179437800     object_id: 70284189056180
  70284179437800     opts:
  70284179437800       {}
  70284179437800       frequency: 0.3
  70284179437800       scheduler_lock: #<Rufus::Scheduler::NullLock:0x007fd8a03e7620>
  70284179437800       trigger_lock: #<Rufus::Scheduler::NullLock:0x007fd8a03e75f8>
  70284179437800     uptime: 32.072310951 (32s72)
  70284179437800     down?: false
  70284179437800     threads: 2
  70284179437800       thread: #<Thread:0x007fd8a03e75a8>
  70284179437800       thread_key: rufus_scheduler_70284189056180
  70284179437800       work_threads: 1
  70284179437800         active: 1
  70284179437800         vacant: 0
  70284179437800         max_work_threads: 28
  70284179437800       mutexes: {}
  70284179437800     jobs: 2
  70284179437800       at_jobs: 0
  70284179437800       in_jobs: 0
  70284179437800       every_jobs: 2
  70284179437800       interval_jobs: 0
  70284179437800       cron_jobs: 0
  70284179437800     running_jobs: 1
  70284179437800     work_queue: 0
} 70284179437800 .
```
I let it run for about 20 seconds and stopped it close after the error occured.

And when I run the sqlite command I get 374 lines ending in:
```
374||2016-05-09 21:22:36.903631|infamy.linuxlookup.com|10240|1
```

**Comment by Kennric** [comment]
This is looking pretty good - I think there are a couple of things we should do for efficiency, but we may want to create new issues for those things in order to get this in and working. Specifically, making the scheduler generically run all extant plugins and creating a global redis connection instead of doing that in each method that uses it (possibly deprecated in favor of json storage in postgres). 

+1

**Comment by alxngyn** [comment]
+1, works for me

```
sqlite> select * from disk_size_measurements;
...
179||2016-05-10 16:30:24.685688|mail.ntf.osuosl.org|12288|1
180||2016-05-10 16:30:24.821239|camo1.phpbb.com|10240|1
181||2016-05-10 16:30:24.971247|chiral.oftc.net|26112|1
182||2016-05-10 16:30:25.113408|rtvloadtest-web2.osuosl.org|21504|0
183||2016-05-10 16:30:25.238815|facebook1.osuosl.org|30720|1
184||2016-05-10 16:30:25.372561|amahi.osuosl.org|15360|1
185||2016-05-10 16:30:25.514682|rtvprodvr-web3.osuosl.org|11264|0
186||2016-05-10 16:30:25.648836|etherpad-lite.osuosl.org|10240|1
187||2016-05-10 16:30:25.807266|whitealder.osuosl.org|23552|1
188||2016-05-10 16:30:25.949675|ucc.osuosl.org|10240|1
189||2016-05-10 16:30:26.108175|infamy.linuxlookup.com|10240|1

sqlite> .schema disk_size_measurements 
CREATE TABLE `disk_size_measurements` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `node_resource` integer, `created` timestamp NOT NULL, `node` varchar(255), `value` integer, `active` Boolean);

sqlite> Select count(*) from disk_size_measurements;
189

```

**Comment by alxngyn** [comment]
I take that back,
lets get the rubocop complaints fixed
my +1 once all/most the fixes goes in
```
[root@3422e0164588 code]# rubocop
Inspecting 14 files
C..CCW......WC

.... offenses ....

14 files inspected, 74 offenses detected
```

**Comment by ElijahCaine** [comment]
@alxngyn Do you know if we can add rubocop runs to a TravisCI run?

**Comment by matthewrsj** [comment]
@alxngyn @Kennric @ElijahCaine  I fixed most of the rubocop complaints about my files. I left some:

- Any complaint pertaining to files not in the scope of this PR
- Complexity/method too long complaints until we decide how we should handle these

Also, please review naming schemes here and in #43. They differ and conflict. I changed the naming to what I believe follows ruby standards closer but I could be wrong.

**Comment by ElijahCaine** [comment]
When I run `rake spec` I get this output:
```
[root@9a02ddb73594 code]# rake spec
/usr/local/bin/ruby -I/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/usr/local/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec spec/models/client_spec.rb spec/routes/app_spec.rb spec/routes/client_spec.rb --format documentation

The Client Model and table
  initially has no clients
  has a model name
  can create a client
  cannot create two clients with the same name
  can create two clients with different names
  cannot create a client without required fields
  cannot create a client without required fields
  can delete a client
  can update a client
  cannot update a client to have a non-unique name

The IAM Application
  says hello

The Client list endpoint
"Client X"
  responds OK
"Client X"
  contains the name of a client we added

Finished in 0.07504 seconds (files took 0.55616 seconds to load)
13 examples, 0 failures

/usr/local/bin/ruby -I/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/usr/local/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec plugins/disk_sizes/spec.rb --format documentation

DiskSize
  .register does not raise an error when invoked
  .register actually actually creates a disk_size_measurements table
  .store does not fail with valid data
  .store fails when not passed node name
undefined method `tr' for nil:NilClass
  .store does not crash when passed improperly formatted data
  .store properly sums all disk sizes when storing in DB
  .report

Finished in 0.04721 seconds (files took 0.52975 seconds to load)
7 examples, 0 failures
```

I'm not sure if `undefined method 'tr' for nil:NilClass` is important.

Everything else looks good +1 from me. We will need to resolve the rubocop problems soon, but I can understand why you chose not to touch code unrelated to the PR.

**Comment by matthewrsj** [comment]
@ElijahCaine that `undefined method 'tr' for nil:NilClass` is an error I'm creating and suppressing in the tests (but logging to STDERR) so it doesn't crash IAM if Ganeti sends bad data.

**Comment by Kennric** [comment]
This looks good, naming is indeed correct now, and I don't see any critical issues with the code. +1

**Pull request merged**
