### PR TITLE
changed travis to 2.2.3

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #xx

## Changes in this PR.

- [X] Foo
- [X] Bar
- [ ] Baz

## Testing this PR.

1. Do X.
2. Do Y.
3. See Z.

### Expected Output.

```
$ rake spec
[...]
```

@osuosl/devs

### CODE REVIEW

**Comment by ElijahCaine** [comment]
Why?

**Comment by Kennric** [comment]
@ElijahCaine ruby 2.3.0 was our original ruby target, but this was changed to 2.2.2 for, I think, Travis reasons. I asked @alxngyn to look into moving it back to 2.3.0 for my deployment convenience. I think he may have misheard and changed to 2.2.3 instead - this PR was just him testing that Travis didn't mind the change.

Also, the the current version string in the Gemfile, ">= 2.2.2", is incorrect syntax and causes errors.

**Comment by ElijahCaine** [comment]
Okay, that all makes sense.  There were definitely a few hacks to get Travis to work.  Let me know if you want to update the container to match this Ruby version.

**Comment by alxngyn** [comment]
@Kennric oops. 
I heard 2.3.0 but processed it to 2.2.3
I'll close all this and open a new branch

**Pull request closed without merging**
