### PR TITLE
Kennric/summary fixes

### PR DESCRIPTION
**Pull request by Kennric**
fixes issue #225 

## Changes in this PR.

- [X] Creates plugin matrix and project report methods in a Report class in util

## Testing this PR.

1. call the project report method with the name of a project 

### Expected Output.

receive a hash of its resources and their measurements

```
$ rake spec
[...]
```

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
@alxngyn, @hsolorza

**Comment by hsolorza** [comment]
When I try to view a client that has a project I get this error:
undefined method `resource_resources' for #<Project:0x007f8c01f78598> Did you mean? resources=
     file: util.rb location: block in project_data line: 150

**Comment by alxngyn** [comment]
getting the same client error as @hsolorza 
ss of the backtrace
fireshot capture 23 - nomethoderror at _clients_1 - http___localhost_4567_clients_1

**Comment by Kennric** [comment]
This is caused by the existence of the Testing Plugin, which the base plugin spec uses for testing the base plugin methods. The testing plugin declares that it measures resources of type "resource". Since we now explicitly relate projects to resource types, but have not created a relationship from projects to "resource" resources, this breaks when the report code tries to find a project's "resource" resources  by calling projects.resource_resources. 

This was not breaking on staging when I was testing, because I changed the testing plugin's resource type to node on staging (this breaks spec on docker, because the testing plugin migration still creates a 'resource' column in its measurement table, note a 'node' one.

The solution, I think, is simply to skip the testing plugin in the code that gathers all the plugins and their available measurements.

**Comment by hsolorza** [comment]
+1

**Comment by alxngyn** [comment]
++

**Pull request merged**
