### PR TITLE
Billing units

### PR DESCRIPTION
**Pull request by hsolorza**
fixes issue #266 #265 #267 

## Changes in this PR.

- [X] Units now present
- [X] Fix billing logic for Database
- [X] DRBD indicator

## Testing this PR.

1. View current month
2.  There are no measurements for current  month so plugins show N/A.

3. View month range from Nov - June
4.  Database values, if less than 1, should show 1 (actual value).

### Expected Output.

```
$ rake spec
[...]
```

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
@ramereth - question: if no data is found in the database for a time range, should that round to 1 as well? No data would seem to indicate that the host is no longer extant.

**Comment by ramereth** [comment]
@Kennric no, it should probably display ``N/A``

**Comment by ramereth** [comment]
@hsolorza I like how you put the actual size in parens for the database information. I wonder if we should do the same for hosts that have DRBD. Show the actual size in parens and the size to the left is the calculated size for billing.

**Comment by ramereth** [comment]
@hsolorza I think having some kind of description about what the values in ``()`` mean would be good. Something like _Values between () are actual values compared to billable values which vary on the fee type. Please see fee book for more information_.

**Pull request merged**
