### PR TITLE
Project pagination 

### PR DESCRIPTION
**Pull request by hsolorza**
fixes issue #226

## Changes in this PR.

- [x] Add paginated page for nodes
- [x] Add paginated page for databases
- [x] Create get_Data method for a specific resource

## Testing this PR.

1. Run app
2. View a project
3. Go to either DB or Node summary
4. See pagination ( change the @per_page var in routes to see the page numbers change)

### Expected Output.

```
$ rake spec
[...]
```

@osuosl/devs

### CODE REVIEW

**Comment by hsolorza** [comment]
@alxngyn  @Kennric  There seems to be an issue showing the pagination in the views. I've followed the documentation https://github.com/mislav/will_paginate/wiki but I am still unable to get the views to work beause when I do `<%= will_paginate @nodes %>`,   I get `undefined method 'will_paginate' for #<Iam:0x007fb2483b38a8> `. Does anyone has any suggestions on what I might be missing?

**Comment by alxngyn** [comment]
https://github.com/mislav/will_paginate/wiki/Installation
I think you might have a sinatra specific issue

**Comment by alxngyn** [comment]
After loading some test data and trying to go into a project's detail page, I'm getting

```
url: http://localhost:4567/projects/2/page/

Sinatra doesn’t know this ditty.
Try this:
# in environment.rb
class Iam
  get '/projects/2/page/' do
    "Hello World"
  end
end

```

**Comment by alxngyn** [comment]
I got around the last error and I see this:
project detail:
download 3

node summary:
download 4

Pagination finally works! 


Just some fixes then I'll +1:
- Fix the project routing
- Remove all the nodes from the project summary page

**Comment by alxngyn** [comment]
+1

**Pull request merged**
