### PR TITLE
Sinatra framework + rake/rubocop

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #8

## Changes in this PR.
- [X] Pulled in Kennric/example sinatra framework
- [X] Ran Rubocop on the entire project and fixed any styling
- [X] Created makefile to automate docker-compose builds/run/up/down
- [x] Integrate rSpec

## Testing this PR.
1. To build and run the app:  
`rake build`   
`rake run`  
2. Once you're inside the docker container, you can just run the app with 
`ruby /data/code/app.rb`
3. To exit the container:  `exit`

## Notes
* app will still run even if robocop complains

### CODE REVIEW

**Comment by matthewrsj** [comment]
@alxngyn you should coordinate with @ElijahCaine. I believe he is doing a lot of the models/migrations that are included in here. The way we will be doing migrations makes some of this obsolete (I believe).

**Comment by Kennric** [comment]
The Rakefile looks good, but lets get @ElijahCaine's models in, and then rebase on his new migrations/models file - also, the testo plugin should come out of this, we should keep 'testo' things in example branches and out of develop

**Comment by alxngyn** [comment]
@Kennric Okay, I'll make this PR smaller after the models merge in

**Comment by Kennric** [comment]
This pr has been divided into several pieces, the last piece, RSpec integration is in #42 - close this when that is merged.

**Comment by Kennric** [comment]
Actually, I think #40 meets the requirement of integrating rspec. Closing.

**Pull request closed without merging**
