### PR TITLE
Added testing mysql and postgres dbs w/ docker

### PR DESCRIPTION
**Pull request by ElijahCaine**
Works on #134

This pull request adds a postgres and mysql testing database for use in IaM's database resource. With these databases (running in linked docker containers) we can test our collector and the queries it runs.

- **Advantages to this**: We know with much greater certainty that our queries are correct.
- **Disadvantages**: Automated testing with Travis will need to either omit the tests that touch docker *or* our testing will take much longer (it's an artifact of how Travis does testing involving containers).

## Changes in this PR.
- [X] Added `wait-for-it.sh` which gets run when `docker-compose up dev` is
  run.
  - This stops the `dev` container from running the spec tests until the
    mysql DB (and hopefully the postgres DB) has started.
  - TLDR automated spec tests with one command.
- [X] Added some examples of how to use the testing mysql and postgres
  databases. Use them by running `docker-compose run dev bash`,
  navigate to the `examples` directory and run `ruby mysql.rb` or
  `ruby psql.rb`. The output is a ruby hash of what the test tables
  contain.
- [X] Added environment variables for the new DB containers.
- [ ] (optional) Add an example of creating a database to `examples/mysql.rb` and
  `examples/psql.rb`.

## Testing this PR.

1. `docker-compose build`
2. `cp dockerfiles/app.env.dist dockerfiles/app.env`
3. `docker-compose run dev bash`
4. (separate terminal)
  - `docker-compose ps`
  - `docker-compose logs -f`
5. (original terminal)
  - `cd examples/`
  - `ruby mysql.rb`
  - `ruby psql.rb`
6. Read `examples/README.md`

### Expected Output.

(1). Build does not fail.
(4). 
```
$ docker-compose ps
         Name                       Command               State    Ports   
--------------------------------------------------------------------------
voigte_dev_run_1         /wait-for-it.sh -q testing ...   Up               
voigte_testing-mysql_1   docker-entrypoint.sh mysqld      Up      3306/tcp 
voigte_testing-psql_1    /docker-entrypoint.sh postgres   Up      5432/tcp
```
```
$ docker-compose logs
[ ... ]
testing-psql_1   | LOG:  database system is ready to accept connections
[ ... ]
testing-mysql_1  | 2016-08-02T18:27:48.349096Z 0 [Note] mysqld: ready for connections.
testing-mysql_1  | Version: '5.7.13'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```
(5). 
```
[root@5bedddb8748d examples]# ruby mysql.rb 
{:id=>2, :name=>"Barby"}
{:id=>3, :name=>"Bazby"}
{:id=>1, :name=>"Fooby"}
{:"DB Name"=>"information_schema", :"Data Base Size in Bytes"=>"163840.0"}
{:"DB Name"=>"test_db", :"Data Base Size in Bytes"=>"49152.0"}
[root@5bedddb8748d examples]# ruby psql.rb 
{:id=>1, :name=>"Fooby"}
{:id=>2, :name=>"Barby"}
{:id=>3, :name=>"Bazby"}
```
@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
i get this error when i run mysql.rb
```
[root@537ebdd20811 code]# cd examples/
[root@537ebdd20811 examples]# ruby mysql.rb
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/adapters/mysql.rb:102:in `real_connect': Mysql::Error: Host '172.18.0.4' is not allowed to connect to this MySQL server (Sequel::DatabaseConnectionError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/adapters/mysql.rb:102:in `connect'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool.rb:103:in `make_new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:224:in `make_new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:197:in `available'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:133:in `_acquire'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:147:in `block in acquire'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:265:in `block in sync'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:265:in `synchronize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:265:in `sync'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:146:in `acquire'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in `synchronize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/adapters/mysql.rb:157:in `execute_dui'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/database/query.rb:45:in `execute_ddl'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/database/schema_methods.rb:666:in `create_table_from_generator'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/database/schema_methods.rb:197:in `create_table'
	from mysql.rb:17:in `<main>'
```
it didn't look like mysql was having any errors on the db side:
```
testing-mysql_1  | 2016-08-02T20:40:15.401012Z 0 [Note] mysqld: ready for connections.
testing-mysql_1  | Version: '5.7.13'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```


i do get success with psql.rb though:
```
[root@537ebdd20811 examples]# ruby psql.rb
{:id=>1, :name=>"Fooby"}
{:id=>2, :name=>"Barby"}
{:id=>3, :name=>"Bazby"}
```

**Comment by alxngyn** [comment]
here is my env:
```
[root@e75f65c870a1 examples]# env
HOSTNAME=e75f65c870a1
TERM=xterm
POSTGRES_DB=test_db
MYSQL_DATABASE=test_db
MYSQL_PASSWORD=test_db_pass
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
POSTGRES_PASSWORD=test_db_pass
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/data/code/examples
POSTGRES_USER=test_db_user
CACHE_FILE=/tmp/iam-cache
MYSQL_RANDOM_ROOT_PASSWORD=yes
HOME=/root
SHLVL=1
LESSOPEN=||/usr/bin/lesspipe.sh %s
MYSQL_USER=test_db_user
DATABASE_URL=sqlite://dev.db
POSTGRES_HOST=172.18.0.5
_=/usr/bin/env
OLDPWD=/data/code
```

**Comment by cthalmann** [comment]
:+1: works for me.

**Comment by alxngyn** [comment]
works for me
docker-compose kill and rm fixed it

**Pull request merged**
