### PR TITLE
update dist docker env for testing mysql collection

### PR DESCRIPTION
**Pull request by Kennric**
fixes issue #194 

## Changes in this PR.

- [X] set up env variables in docker's app.env.dist that should work for testing with the docker-compose setup

## Testing this PR.

1. copy dockerfiles/app.env.dist to dockerfiles/app.env
2. `docker-compose up`

### Expected Output.

All tests will pass, including db collector tests, which previously were skipped.

@osuosl/devs

### CODE REVIEW

**Comment by hsolorza** [comment]
The tests are still failing for me, the collector tests fail with https://pastebin.osuosl.org/43896/81238194/  and all the others say https://pastebin.osuosl.org/43891/48123814/

**Comment by hsolorza** [comment]
Actually, I had an untracked file following me around messing up the tests. Now when I run it, the two collector tests still fail with the same error, but all the others pass.

**Comment by Kennric** [comment]
Rebased and working. Note, this still doesn't run the app, it just makes the mysql collector tests pass.

**Comment by Kennric** [comment]
@alxngyn can you verify this works?

**Comment by alxngyn** [comment]
```
dev_1           | Finished in 15.93 seconds (files took 1.28 seconds to load)
dev_1           | 121 examples, 0 failures
```

all tests pass for me

**Comment by hsolorza** [comment]
+1

**Comment by Kennric** [comment]
@hsolorza no difference, just moved the line

**Comment by hsolorza** [comment]
+1

**Pull request merged**
