### PR TITLE
Create Collectors class with collect_ganeti method

### LINKED ISSUE #10: [8] Ruby method to query ganeti API for all ganeti clusters
This works from a workstation: 

```
curl -k https://ganeti-psf.osuosl.bak:5080/2/instances?bulk=1
```

We need to do this in ruby against all our clusters. A simple ruby equivalent to the curl command above is:

```
require 'net/http'
require 'uri'
require 'openssl'
 
url = 'https://ganeti-psf.osuosl.bak:5080/2/instances?bulk=1'
uri = URI(url)
 
Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https',
                :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|
    request = Net::HTTP::Get.new uri
    response = http.request request
    puts response.body
end
```

General workflow
================

Pre-processing
--------------

1. Query for all nodes in our `RESOURCES` table with a unique string in the `cluster` field.
2. Run a GET request against each`<cluster-fqdn>/<ganeti-version>/instances?bulk=1`
3. Store the returned JSON in a cache such as redis (http://redis.io/documentation) with the cluster name and a datetime.

Gather metrics
--------------

1. Query all nodes in our `RESOURCES` table.  
    **if** node's `cluster` field is **not** `null`, query our cache at `clustername`  
    **else** do what we are supposed to do for that node type
2. Process data returned from step 1
3. Store in database.

### PR DESCRIPTION
**Pull request by matthewrsj**
1. Instantiate a redis instance
2. Read the `datastruct.erb` file into `@template` variable
3. for each ganeti cluster
  - GET request with `?bulk=1`
  - for each node in cluster
    * Read relevant data
    * Store in redis at `node_name`
    * Store time recorded at `node_name:datetime`

Fixes #10

### CODE REVIEW

**Comment by Kennric** [comment]
Please create an issue for this.

**Comment by matthewrsj** [comment]
@Kennric issue #10 already exists

**Comment by matthewrsj** [comment]
Sample output of `JSON.parse(@redis.get(node_name))` for all nodes in `ganeti` cluster (very small sample, total is 189 lines):

```
{"disk_sizes"=>"[20480]", "disk_usage"=>"20480", "disk_template"=>"plain", "num_cpus"=>"2", "total_ram"=>"512"}
{"disk_sizes"=>"[10240]", "disk_usage"=>"10368", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"1024"}
{"disk_sizes"=>"[10240]", "disk_usage"=>"10368", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"512"}
{"disk_sizes"=>"[51200]", "disk_usage"=>"51328", "disk_template"=>"drbd", "num_cpus"=>"4", "total_ram"=>"2048"}
{"disk_sizes"=>"[19456]", "disk_usage"=>"19584", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"4096"}
{"disk_sizes"=>"[17408, 102400]", "disk_usage"=>"120064", "disk_template"=>"drbd", "num_cpus"=>"6", "total_ram"=>"8192"}
{"disk_sizes"=>"[30720]", "disk_usage"=>"30848", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"2048"}
{"disk_sizes"=>"[8704]", "disk_usage"=>"8832", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"512"}
{"disk_sizes"=>"[23552]", "disk_usage"=>"23680", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"3072"}
{"disk_sizes"=>"[107520]", "disk_usage"=>"107648", "disk_template"=>"drbd", "num_cpus"=>"8", "total_ram"=>"4096"}
{"disk_sizes"=>"[81920]", "disk_usage"=>"82048", "disk_template"=>"drbd", "num_cpus"=>"4", "total_ram"=>"4096"}
{"disk_sizes"=>"[55296, 51200]", "disk_usage"=>"106752", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"4096"}
{"disk_sizes"=>"[55296]", "disk_usage"=>"55424", "disk_template"=>"drbd", "num_cpus"=>"8", "total_ram"=>"4096"}
{"disk_sizes"=>"[20480]", "disk_usage"=>"20608", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"2048"}
{"disk_sizes"=>"[31744]", "disk_usage"=>"31872", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"1024"}
{"disk_sizes"=>"[10752]", "disk_usage"=>"10880", "disk_template"=>"drbd", "num_cpus"=>"2", "total_ram"=>"512"}
```

**Comment by alxngyn** [comment]
Good work @matthewrsj ! Looks good and useful.

I think we should package the data into one JSON file and label each vm with it's ["name"] parameter.

**Comment by matthewrsj** [comment]
@alxngyn well, we are packaging the data into redis using the `node_name` as the key. That will be our local data. Once we have that we will run plugins against the redis to get out the measurements and put into a database.

**Comment by ElijahCaine** [comment]
Adding `puts JSON.parse(@redis.get(node_name))` below the `@redis.mset(...)` line output data similar to what @matthewrsj mentioned above, so a +1 from me.

**Comment by alxngyn** [comment]
+1 
Looks good so far! This is what I got from testing:

>127.0.0.1:6379> KEYS *bak
>1) "jenkins-test1.osuosl.bak"
>2) "jenkins-test2.osuosl.bak"
>127.0.0.1:6379> GET jenkins-test1.osuosl.bak
>"{\"disk_sizes\": \"[5120]\", \"disk_usage\": \"5120\", \"disk_template\": \"plain\", \"num_cpus\": \"2\", >\"total_ram\": \"512\" }\n"

**Comment by matthewrsj** [comment]
Waiting on #16 to merge

**Pull request merged**
