### PR TITLE
Add DiskTemplate plugin

### LINKED ISSUE #74: DiskTemplate plugin
Records if it is DRBD or not (0 or 1 or t/f)

### PR DESCRIPTION
**Pull request by matthewrsj**
fixes #74 

## Changes in this PR.

- [X] Add DiskTemplate `plugin.rb`
- [X] Add DiskTemplate migrations
- [X] Add DiskTemplate spec tests

## Testing this PR.

1. `docker-compose run dev bash`
2. `rake spec`

### Expected Output.

```
$ rake spec
[... passing tests ...]

DiskTemplate plugin
  .register method
    does not raise an error when invoked
    creates a disk_template_measurements table
  .store method
    does not fail with valid data
    fails when not passed node name
No disk_template information for badnode: {"disk_type"=>"1", "active"=>true}
    does not crash when passed improperly formatted data
    stores the right thing in the value field
  .report method
    should return data on all nodes for the last day by default
    returns data on a known specific nodes for 1 day
    returns empty on unknown node
    should return TypeError on invalid day input

[... passing tests ...]
```

@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
+1 
I think the name should be diskType instead of diskTemplate but it doesn't matter

**Comment by matthewrsj** [comment]
@alxngyn I went with disk template because that is what ganeti calls it. I believe `template` is more descriptive than `type` anyways.

**Comment by ElijahCaine** [comment]
Output matches that listed in the PR.
Tests look solid. Implementation looks good too.
+1 from me.

**Comment by ElijahCaine** [comment]
Output matches that listed in the PR.
Tests look solid. Implementation looks good too.
+1 from me.

**Pull request merged**
