### PR TITLE
plugin register method and added REDIS environment.rb var

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #32 

## Changes in this PR.

- [X] Added REDIS to environment.rb
- [X] Added plugin.rb w/ migration file

## Testing this PR.

1. Open `plugins/disk_sizes/plugin.rb` and uncomment the last line
2. Run docker container, `docker-compose run dev bash`
3. Run `rake migrate`
4. Since app.rb isn't migrating plugins yet, run: `$ ruby plugins/disk_sizes/plugin.rb`
5. Open sqlite3 database, `$ sqlite3 /tmp/development.sqlite`
6. There should be 3 changes:
 * `measurementDiskSizes` table should've been created
 * a row in the table `plugins` was created for DiskSize
 * version recorded in `schema_info` (used by Sequel::Migration tracking/rollbacks)

Expected Output
```
sqlite> .tables
clients node_resources projects measurementDiskSizes plugins schema_info   
      
sqlite> select * from plugins;
1|DiskSizes|node|disk_sizes|bytes

sqlite> .schema schema_info
CREATE TABLE `schema_info` (`version` integer DEFAULT (0) NOT NULL, `diskSize_ver` integer DEFAULT (0) NOT NULL);

sqlite> select version, diskSize_ver from schema_info;
1|1
```

@Kennric @matthewrsj @ElijahCaine @mathuin

### CODE REVIEW

**Comment by matthewrsj** [comment]
Well, the code looks good, but I'm getting this error when running `rake migrate`:

```
[root@4a57e9039b0c code]# rake migrate --trace
** Invoke migrate (first_time)
** Execute migrate
rake aborted!
NoMethodError: undefined method `[]' for <Rake::Task migrate => []>:Rake::Task
/data/code/Rakefile:13:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:246:in `block in execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => migrate
```
Did you locally modify the Rakefile or Gemfile?

**Comment by alxngyn** [comment]
@matthewrsj 
My bad, I must've locally modified the rakefile when I was testing. That error should be is fixed in PR #41.

**Comment by matthewrsj** [comment]
@alxngyn can you rebase to include that fix now that #41 has been merged?

**Comment by matthewrsj** [comment]
Everything works as expected, if we need to change anything later we can do so. +1.

**Comment by matthewrsj** [comment]
+1 again (explicitly on @alxngyn's code)

**Comment by Kennric** [comment]
+1

**Pull request merged**
