### PR TITLE
Removed & ignored logging

### LINKED ISSUE #151: gitignore logging/
I think we should gitignore logging/ directory otherwise someone might accidentally commit theirs into the repo
OR
should we be commiting our logs to save history or something?

### PR DESCRIPTION
**Pull request by ElijahCaine**
fixes #151

## Changes in this PR
- [x] Removed logging directory from repo
- [x] Added `logging/` to `.gitignore` file

@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
@ElijahCaine My fault I didn't do a thorough research with this.
I think we should gitnore the logging file and not the whole directory. There is @hsolorza's logging work & spec were deleting here

**Comment by ElijahCaine** [comment]
@alxngyn fixed.

**Comment by alxngyn** [comment]
+1

**Comment by hsolorza** [comment]
+1

**Pull request merged**
