### PR TITLE
Pinned all gems to a version on a working build

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #120 

## Changes in this PR.

- [X] Pinned all gems to a specific version from a working build

## Testing this PR.

1. Do docker
2. If this is your first run in this branch, do a bundle install and it should install all the specific gems
3. Do `rake`
4. It should just work and not complain about gem versions/not found/etc

### Expected Output.

```
$ rake spec
[ ...successful output goes here ]

### CODE REVIEW

**Comment by ElijahCaine** [comment]
This PR is out of date, or will very quickly become out of date with #145 getting merged.
Do we think this should get merged or should we scrap it?

**Comment by alxngyn** [comment]
I think we should pin them and upgrade each gems version if we need a specific feature or security update. 
@Kennric thoughts?

**Comment by Kennric** [comment]
@alxngyn @ElijahCaine yeah, if we are running into version issues, we should pin and re-pin as needed

**Comment by ElijahCaine** [comment]
@alxngyn Can we please merge this soon? If you don't want to do it I will, I don't want to step on your toes though.

**Comment by hsolorza** [comment]
+1 lgtm

**Comment by ElijahCaine** [comment]
Tests pass when you run `docker-compose build --no-cache --pull && docker-compose up dev` so I'm gonna give this a +1.

**Pull request merged**
