### PR TITLE
Moving all routes to the `routes/` directory

### PR DESCRIPTION
**Pull request by ElijahCaine**
fixes issue #69 

## Changes in this PR.

- [X] Factor all routes to appropriate `.rb` files in the `routes/` directory.
- [X] Client Routes
- [X] Top Level Routes
- [X] Project Routes
- [X] Pass Tests

## Testing this PR.

1. Log into the development environment.
2. `rake spec`
3. Tests *should* pass.

### Expected Output.

```
$ rake spec
[... some pases and the following failures: ...]
rspec ./spec/routes/client_spec.rb:31 # The Clients endpoint displays a specific client by id
rspec ./spec/routes/client_spec.rb:42 # The Clients endpoint responds ok when asked for clients/new
rspec ./spec/routes/client_spec.rb:58 # The Clients endpoint allows us to create a new client, then redirects to the list
rspec ./spec/routes/client_spec.rb:73 # The Clients endpoint allows us to edit a client, then redirects to the list
rspec ./spec/routes/client_spec.rb:91 # The Clients endpoint allows us to edit a single client field then redirects to the list
```

@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
Looks great Elijah. +1

Side note: 
I think we should get a middleware API running before this so we can have http logging, auth when we build out, etc

**Comment by matthewrsj** [comment]
@ElijahCaine did you want to rebase and move the projects endpoints over as well?

**Comment by ElijahCaine** [comment]
@alxngyn @matthewrsj Take another look at this PR if you could.

I tried rebasing and it caused some funky commits from develop to be included in this PR so I removed those commits. This now does not delete the projects code from app.rb (or maybe it will?) but it does include that code in `routes/projects.rb`.

Feedback or +1 when you have a chance.

**Comment by alxngyn** [comment]
I'm failing one test at the `/clients` endpoint

```
[root@feaa7a49be0a code]# rake spec
 ...
The Clients endpoint
  responds OK
  includes the names of existing clients (FAILED - 1)
  displays a specific client by id
  answers 404 when asked for a non-existent client
  responds ok when asked for clients/new
  responds ok when asked for the form to edit an existing client
  responds 404 when asked for the form to edit an absent client
  allows us to create a new client, then redirects to the list
  allows us to edit a client, then redirects to the list
  allows us to edit a single client field then redirects to the list

Failures:

  1) The Clients endpoint includes the names of existing clients
     Failure/Error: expect(last_response.body).to include('Client X')
       expected "" to include "Client X"
     # ./spec/routes/client_spec.rb:26:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:56:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'

Finished in 0.23118 seconds (files took 0.50456 seconds to load)
41 examples, 1 failure

Failed examples:

rspec ./spec/routes/client_spec.rb:19 # The Clients endpoint includes the names of existing clients

/usr/local/bin/ruby -I/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/usr/local/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec plugins/DiskSize/spec.rb plugins/VCPUCount/spec.rb spec/models/client_spec.rb spec/routes/app_spec.rb spec/routes/client_spec.rb --format documentation failed

```

**Comment by ElijahCaine** [comment]
@alxngyn I did not get any failures after running
```
[local system] $ docker-compose build --no-cache --pull
[local system] $ docker-compose run dev bash
[container] # rake spec

**Comment by alxngyn** [comment]
After rebasing my local git repo, I got that test to pass. +1

**Pull request merged**
